//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRAIN.SIMAX.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMStudent()
        {
            this.DMSubjectStudents = new HashSet<DMSubjectStudent>();
        }
    
        public string ID { get; set; }
        public string IDClass { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Address { get; set; }
        public string BirthDay { get; set; }
        public string Phone { get; set; }
        public string Sex { get; set; }
    
        public virtual DMClass DMClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMSubjectStudent> DMSubjectStudents { get; set; }
    }

    public partial class DMStudentEntities
    {
        public string ID { get; set; }
        public string IDClass { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Address { get; set; }
        public string BirthDay { get; set; }
        public string Phone { get; set; }
        public string Sex { get; set; }
    }
}
