//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRAIN.SIMAX.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMSubjectStudent
    {
        public int ID { get; set; }
        public string IDStudent { get; set; }
        public string IDSubject { get; set; }
    
        public virtual DMStudent DMStudent { get; set; }
        public virtual DMSubject DMSubject { get; set; }
    }

    public partial class DMSubjectStudentEntities
    {
        public int ID { get; set; }
        public string IDStudent { get; set; }
        public string IDSubject { get; set; }
    }
}
