//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRAIN.SIMAX.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMSubject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMSubject()
        {
            this.DMSubjectStudents = new HashSet<DMSubjectStudent>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMSubjectStudent> DMSubjectStudents { get; set; }
    }

    public partial class DMSubjectEntities
    {
        public string ID { get; set; }
        public string Name { get; set; }
    }

}
