//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRAIN.SIMAX.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManageStudentEntities : DbContext
    {
        public ManageStudentEntities()
            : base("name=ManageStudentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DMClass> DMClasses { get; set; }
        public virtual DbSet<DMStudent> DMStudents { get; set; }
        public virtual DbSet<DMSubject> DMSubjects { get; set; }
        public virtual DbSet<DMSubjectStudent> DMSubjectStudents { get; set; }
    }
}
